# Usa o Nginx super leve
FROM nginx:alpine

# Copia os arquivos de dentro da sua pasta frontend para a raiz do Nginx
COPY ./frontend /usr/share/nginx/html

# Libera a porta padrão de internet
EXPOSE 80